config/routes.rb
      resource :version, :path => ":version", :version => /\d+/, :controller => :old_nodes, :only => :show do
        resource :redaction, :module => :old_nodes, :only => [:create, :destroy]
      end
    end
    put "node/create" => "nodes#create", :as => nil
    post "node/:node_id/:version/redact" => "old_nodes/redactions#create", :node_id => /\d+/, :version => /\d+/, :allow_delete => true, :as => nil

    resources :ways, :only => [:index, :create]
    resources :ways, :path => "way", :id => /\d+/, :only => [:show, :update, :destroy] do
      member do
        get :full, :action => :show, :full => true, :as => nil
      end
      scope :module => :ways do
        resources :relations, :only => :index
      end
      resources :versions, :path => "history", :controller => :old_ways, :only => :index
      resource :version, :path => ":version", :version => /\d+/, :controller => :old_ways, :only => :show do
        resource :redaction, :module => :old_ways, :only => [:create, :destroy]
      end
    end
    put "way/create" => "ways#create", :as => nil
    post "way/:way_id/:version/redact" => "old_ways/redactions#create", :way_id => /\d+/, :version => /\d+/, :allow_delete => true, :as => nil

    resources :relations, :only => [:index, :create]
    resources :relations, :path => "relation", :id => /\d+/, :only => [:show, :update, :destroy] do
      member do
        get :full, :action => :show, :full => true, :as => nil
      end
      scope :module => :relations do
        resources :relations, :only => :index
      end
      resources :versions, :path => "history", :controller => :old_relations, :only => :index
      resource :version, :path => ":version", :version => /\d+/, :controller => :old_relations, :only => :show do
        resource :redaction, :module => :old_relations, :only => [:create, :destroy]
      end
    end
    put "relation/create" => "relations#create", :as => nil
    post "relation/:relation_id/:version/redact" => "old_relations/redactions#create", :relation_id => /\d+/, :version => /\d+/, :allow_delete => true, :as => nil

    resource :map, :only => :show

    resources :tracepoints, :path => "trackpoints", :only => :index

    resources :users, :only => :index
    resources :users, :path => "user", :id => /\d+/, :only => :show
    resources :user_traces, :path => "user/gpx_files", :module => :users, :controller => :traces, :only => :index
    get "user/details" => "users#details"

    resources :user_preferences, :except => [:new, :create, :edit], :param => :preference_key, :path => "user/preferences" do
      collection do
        put "" => "user_preferences#update_all", :as => ""
      end
    end

    resources :messages, :path => "user/messages", :constraints => { :id => /\d+/ }, :only => [:create, :show, :update, :destroy]
    namespace :messages, :path => "user/messages" do
      resource :inbox, :only => :show
      resource :outbox, :only => :show
    end
    post "/user/messages/:id" => "messages#update", :as => nil

    resources :traces, :path => "gpx", :only => [:create, :show, :update, :destroy], :id => /\d+/ do
      scope :module => :traces do
        resource :data, :only => :show
      end
    end
    post "gpx/create" => "traces#create", :id => /\d+/, :as => :trace_create
    get "gpx/:id/details" => "traces#show", :id => /\d+/, :as => :trace_details

    # Map notes API
    resources :notes, :except => [:new, :edit, :update], :id => /\d+/, :controller => "notes" do
      collection do
        get "search"
        get "feed", :defaults => { :format => "rss" }
      end

      member do
        post "comment"
        post "close"
        post "reopen"
      end

      resource :subscription, :only => [:create, :destroy], :controller => "note_subscriptions"
    end

    resources :user_blocks, :only => [:show, :create], :id => /\d+/, :controller => "user_blocks"
    namespace :user_blocks, :path => "user/blocks" do
      resource :active_list, :path => "active", :only => :show
    end
  end

  # Data browsing
  get "/way/:id" => "ways#show", :id => /\d+/, :as => :way
  get "/way/:id/history" => "old_ways#index", :id => /\d+/, :as => :way_history
  resources :old_ways, :path => "/way/:id/history", :id => /\d+/, :version => /\d+/, :param => :version, :only => :show
  get "/node/:id" => "nodes#show", :id => /\d+/, :as => :node
  get "/node/:id/history" => "old_nodes#index", :id => /\d+/, :as => :node_history
  resources :old_nodes, :path => "/node/:id/history", :id => /\d+/, :version => /\d+/, :param => :version, :only => :show
  get "/relation/:id" => "relations#show", :id => /\d+/, :as => :relation
  get "/relation/:id/history" => "old_relations#index", :id => /\d+/, :as => :relation_history
  resources :old_relations, :path => "/relation/:id/history", :id => /\d+/, :version => /\d+/, :param => :version, :only => :show

  resources :changesets, :path => "changeset", :id => /\d+/, :only => :show do
    resource :subscription, :controller => :changeset_subscriptions, :only => [:show, :create, :destroy]
    namespace :changeset_comments, :as => :comments, :path => :comments do
      resource :feed, :only => :show, :defaults => { :format => "rss" }
    end
  end
  get "/changeset/:id/subscribe", :id => /\d+/, :to => redirect(:path => "/changeset/%{id}/subscription")
  get "/changeset/:id/unsubscribe", :id => /\d+/, :to => redirect(:path => "/changeset/%{id}/subscription")

  resources :notes, :path => "note", :id => /\d+/, :only => [:show, :new]

  get "/user/:display_name/history" => "changesets#index"
  get "/user/:display_name/history/feed" => "changesets#feed", :defaults => { :format => :atom }
  get "/user/:display_name/notes" => "notes#index", :as => :user_notes
  get "/history/friends" => "changesets#index", :friends => true, :as => "friend_changesets", :defaults => { :format => :html }
  get "/history/nearby" => "changesets#index", :nearby => true, :as => "nearby_changesets", :defaults => { :format => :html }

  get "/browse/way/:id",                :to => redirect(:path => "/way/%{id}")
  get "/browse/way/:id/history",        :to => redirect(:path => "/way/%{id}/history")
  get "/browse/node/:id",               :to => redirect(:path => "/node/%{id}")
  get "/browse/node/:id/history",       :to => redirect(:path => "/node/%{id}/history")
  get "/browse/relation/:id",           :to => redirect(:path => "/relation/%{id}")
  get "/browse/relation/:id/history",   :to => redirect(:path => "/relation/%{id}/history")
  get "/browse/changeset/:id",          :to => redirect(:path => "/changeset/%{id}")
  get "/browse/note/:id",               :to => redirect(:path => "/note/%{id}")
  get "/user/:display_name/edits",      :to => redirect(:path => "/user/%{display_name}/history")
  get "/user/:display_name/edits/feed", :to => redirect(:path => "/user/%{display_name}/history/feed")
  get "/browse/friends",                :to => redirect(:path => "/history/friends")
  get "/browse/nearby",                 :to => redirect(:path => "/history/nearby")
  get "/browse/changesets/feed",        :to => redirect(:path => "/history/feed")
  get "/browse/changesets",             :to => redirect(:path => "/history")
  get "/browse",                        :to => redirect(:path => "/history")

  # web site
  root :to => "site#index", :via => [:get, :post]
  get "/edit" => "site#edit"
  get "/copyright/:copyright_locale" => "site#copyright"
  get "/copyright" => "site#copyright"
  get "/welcome" => "site#welcome"
  get "/fixthemap" => "site#fixthemap"
  get "/help" => "site#help"
  get "/about/:about_locale" => "site#about"
  get "/about" => "site#about"
  get "/communities" => "site#communities"
  get "/history" => "changesets#index"
  get "/history/feed" => "changesets#feed", :defaults => { :format => :atom }
  scope "/history" do
    namespace :changeset_comments, :path => :comments, :as => :changesets_comments do
      resource :feed, :only => :show, :defaults => { :format => "rss" }
    end
  end
  get "/export" => "site#export"
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  match "/logout" => "sessions#destroy", :via => [:get, :post]
  get "/offline" => "site#offline"
  resource :map_key, :path => "key", :only => :show
  get "/id" => "site#id"
  resource :feature_query, :path => "query", :only => :show
  post "/user/:display_name/confirm/resend" => "confirmations#confirm_resend", :as => :user_confirm_resend
  match "/user/:display_name/confirm" => "confirmations#confirm", :via => [:get, :post]
  match "/user/confirm" => "confirmations#confirm", :via => [:get, :post]
  match "/user/confirm-email" => "confirmations#confirm_email", :via => [:get, :post]
  post "/user/go_public" => "users#go_public"
  scope :user, :as => "user" do
    get "forgot-password" => "passwords#new"
    post "forgot-password" => "passwords#create"
    get "reset-password" => "passwords#edit"
    post "reset-password" => "passwords#update"
  end
  get "/user/suspended" => "users#suspended"

  get "/index.html", :to => redirect(:path => "/")
  get "/create-account.html", :to => redirect(:path => "/user/new")
  get "/forgot-password.html", :to => redirect(:path => "/user/forgot-password")

  # omniauth
  get "/auth/failure" => "users#auth_failure"
  match "/auth/:provider/callback" => "users#auth_success", :via => [:get, :post], :as => :auth_success
  match "/auth/:provider" => "users#auth", :via => [:post, :patch], :as => :auth

  # permalink
  get "/go/:code" => "site#permalink", :code => /[a-zA-Z0-9_@~]+[=-]*/, :as => :permalink

  # rich text preview
  post "/preview/:type" => "site#preview", :as => :preview

  # traces
  resources :traces, :id => /\d+/, :except => [:show] do
    resource :data, :module => :traces, :only => :show
  end
  get "/user/:display_name/traces/tag/:tag/page/:page", :page => /[1-9][0-9]*/, :to => redirect(:path => "/user/%{display_name}/traces/tag/%{tag}")
  get "/user/:display_name/traces/tag/:tag" => "traces#index"

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id          :bigint           not null, primary key
#  latitude    :integer          not null
#  longitude   :integer          not null
#  tile        :bigint           not null
#  updated_at  :datetime         not null
#  created_at  :datetime         not null
#  status      :enum             not null
#  closed_at   :datetime
#  description :text             default(""), not null
#  user_id     :bigint
#  user_ip     :inet
#
# Indexes
#
#  index_notes_on_description             (to_tsvector('english'::regconfig, description)) USING gin
#  index_notes_on_user_id_and_created_at  (user_id,created_at) WHERE (user_id IS NOT NULL)
#  notes_created_at_idx                   (created_at)
#  notes_tile_status_idx                  (tile,status)
#  notes_updated_at_idx                   (updated_at)
#
# Foreign Keys
#
#  notes_user_id_fkey  (user_id => users.id)
#

class Note < ApplicationRecord
  include GeoRecord

  belongs_to :author, :class_name => "User", :foreign_key => "user_id", :optional => true

  has_many :comments, -> { left_joins(:author).where(:visible => true, :users => { :status => [nil, "active", "confirmed"] }).order(:created_at) }, :class_name => "NoteComment", :foreign_key => :note_id
  has_many :all_comments, -> { left_joins(:author).order(:created_at) }, :class_name => "NoteComment", :foreign_key => :note_id, :inverse_of => :note
  has_many :subscriptions, :class_name => "NoteSubscription"
  has_many :subscribers, :through => :subscriptions, :source => :user

  validates :id, :uniqueness => true, :presence => { :on => :update },
                 :numericality => { :on => :update, :only_integer => true }
  validates :latitude, :longitude, :numericality => { :only_integer => true }
  validates :closed_at, :presence => true, :if => proc { :status == "closed" }
  validates :status, :inclusion => %w[open closed hidden]

  validate :validate_position

  scope :visible, -> { where.not(:status => "hidden") }
  scope :invisible, -> { where(:status => "hidden") }

  after_initialize :set_defaults

  DEFAULT_FRESHLY_CLOSED_LIMIT = 7.days

  # Sanity check the latitude and longitude and add an error if it's broken
  def validate_position
    errors.add(:base, "Note is not in the world") unless in_world?
  end

  # Close a note
  def close
    self.status = "closed"
    self.closed_at = Time.now.utc
    save
  end

  # Reopen a note
  def reopen
    self.status = "open"
    self.closed_at = nil
    save
  end

  # Check if a note is visible
  def visible?
    status != "hidden"
  end

  # Check if a note is closed
  def closed?
    !closed_at.nil?
  end

  def freshly_closed?
    return false unless closed?

    Time.now.utc < freshly_closed_until
  end

  def freshly_closed_until
    return nil unless closed?

    closed_at + DEFAULT_FRESHLY_CLOSED_LIMIT
  end

  # Return the note's description
  def description
    RichText.new("text", super)
  end

  private

  # Fill in default values for new notes
  def set_defaults
    self.status = "open" unless attribute_present?(:status)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  include UserMethods

  layout :map_layout

  before_action :check_api_readable
  before_action :authorize_web
  before_action :require_oauth

  authorize_resource

  before_action :lookup_user, :only => [:index]
  before_action :set_locale
  around_action :web_timeout

  ##
  # Display a list of notes by a specified user
  def index
    param! :page, Integer, :min => 1

    @params = params.permit(:display_name, :status)
    @title = t ".title", :user => @user.display_name
    @page = (params[:page] || 1).to_i
    @page_size = 10
    @notes = @user.notes
    @notes = @notes.visible unless current_user&.moderator?
    @notes = @notes.where(:status => params[:status]) unless params[:status] == "all" || params[:status].blank?
    @notes = @notes.order("updated_at DESC, id").distinct.offset((@page - 1) * @page_size).limit(@page_size).preload(:comments => :author)

    render :layout => "site"
  end

  def show
    @type = "note"

    if current_user&.moderator?
      @note = Note.find(params[:id])
      @note_comments = @note.comments.unscope(:where => :visible)
    else
      @note = Note.visible.find(params[:id])
      @note_comments = @note.comments
    end

    @note_includes_anonymous = @note.author.nil? || @note_comments.find { |comment| comment.author.nil? }

    @note_comments = @note_comments.drop(1) if @note_comments.first&.event == "opened"
  rescue ActiveRecord::RecordNotFound
    render :template => "browse/not_found", :status => :not_found
  end

  def new
    @anonymous_notes_count = request.cookies["_osm_anonymous_notes_count"].to_i || 0
    render :action => :new_readonly if api_status != "online"
  end
end

app/helpers/note_helper.rb
module NoteHelper
  include ActionView::Helpers::TranslationHelper

  def note_description(author, description, first_comment)
    if !author.nil? && author.status == "deleted"
      RichText.new("text", t("notes.show.description_when_author_is_deleted"))
    elsif first_comment&.event != "opened"
      RichText.new("text", t("notes.show.description_when_there_is_no_opening_comment"))
    else
      description
    end
  end

  def note_event(event, at, by)
    if by.nil?
      t("notes.show.event_#{event}_by_anonymous_html",
        :time_ago => friendly_date_ago(at))
    else
      t("notes.show.event_#{event}_by_html",
        :time_ago => friendly_date_ago(at),
        :user => note_author(by))
    end
  end

  def note_author(author, link_options = {})
    if author.nil?
      ""
    elsif author.status == "deleted"
      t("users.no_such_user.deleted")
    else
      link_to h(author.display_name), link_options.merge(:controller => "/users", :action => "show", :display_name => author.display_name),
              :class => "mw-100 d-inline-block align-bottom text-truncate text-wrap", :dir => "auto"
    end
  end
end

app/views/notes/_not_found_message.html.erb
<div>
  <p><%= t ".sorry", :id => params[:id] %></p>
</div>

app/views/notes/_notes_paging_nav.html.erb
<nav>
  <% link_class = "page-link icon-link text-center text-nowrap" %>
  <ul class="pagination">
    <% previous_link_content = capture do %>
      <%= previous_page_svg_tag :class => "flex-shrink-0" %>
      <%= t(".previous") %>
    <% end %>
    <% if @page > 1 %>
      <li class="page-item">
        <%= link_to previous_link_content, @params.merge(:page => @page - 1), :class => link_class %>
      </li>
    <% else %>
      <li class="page-item disabled">
        <%= tag.span previous_link_content, :class => link_class %>
      </li>
    <% end %>

    <li class="page-item active">
      <%= tag.span t(".showing_page", :page => @page), :class => link_class %>
    </li>

    <% next_link_content = capture do %>
      <%= t(".next") %>
      <%= next_page_svg_tag :class => "flex-shrink-0" %>
    <% end %>
    <% if @notes.size < @page_size %>
      <li class="page-item disabled">
        <%= tag.span next_link_content, :class => link_class %>
      </li>
    <% else %>
      <li class="page-item">
        <%= link_to next_link_content, @params.merge(:page => @page + 1), :class => link_class %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/notes/index.html.erb
<% content_for :heading do %>
  <h1><%= t ".heading", :user => @user.display_name %></h1>
  <p><%= t ".subheading_html",
           :user => link_to(@user.display_name, @user),
           :submitted => tag.span(t(".subheading_submitted"), :class => "px-2 py-1 bg-primary bg-opacity-25"),
           :commented => tag.span(t(".subheading_commented"), :class => "px-2 py-1 bg-body") %></p>
<% end %>

<%= form_with :url => user_notes_path(@user), :method => :get, :data => { :turbo => true } do %>
  <div class="row gx-2 align-items-end">
    <div class="col-sm-auto mb-3">
      <%= label_tag :status, t(".status") %>
      <%= select_tag :status,
                     options_for_select([[t(".all"), "all"], [t(".open"), "open"], [t(".closed"), "closed"]], params[:status] || "all"),
                     :class => "form-select" %>
    </div>
    <div class="col-sm-auto mb-3">
      <%= submit_tag t(".apply"), :name => nil, :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

<% if @notes.empty? %>
  <h4><%= t ".no_notes" %></h4>

<% else %>
  <%= render :partial => "notes_paging_nav" %>

  <table class="table table-sm note_list">
    <thead>
      <tr>
        <th></th>
        <th><%= t ".id" %></th>
        <th><%= t ".creator" %></th>
        <th><%= t ".description" %></th>
        <th><%= t ".created_at" %></th>
        <th><%= t ".last_changed" %></th>
      </tr>
    </thead>
  <% @notes.each do |note| -%>
    <tr<% if note.author == @user %> class="table-primary"<% end %>>
      <td>
        <% if note.closed? %>
          <%= image_tag("closed_note_marker.svg", :alt => "closed", :width => 25, :height => 40) %>
        <% else %>
          <%= image_tag("open_note_marker.svg", :alt => "open", :width => 25, :height => 40) %>
        <% end %>
      </td>
      <td><%= link_to note.id, note %></td>
      <td><%= note_author(note.author) %></td>
      <td><%= note_description(note.author, note.description, current_user&.moderator? ? note.comments.unscope(:where => :visible).first : note.comments.first).to_html %></td>
      <td><%= friendly_date_ago(note.created_at) %></td>
      <td><%= friendly_date_ago(note.updated_at) %></td>
    </tr>
  <% end -%>
  </table>

  <%= render :partial => "notes_paging_nav" %>

<% end -%>

app/views/notes/new.html.erb
<% set_title(t(".title")) %>

<%= render "sidebar_header", :title => t(".title") %>

<div class="note">
  <p class="alert alert-info"><%= t(".intro") %></p>
  <% if !current_user %>
    <div class="alert alert-warning pb-0">
      <p><%= t ".anonymous_warning_html",
               :log_in => link_to(t(".anonymous_warning_log_in"), login_path(:referer => new_note_path)),
               :sign_up => link_to(t(".anonymous_warning_sign_up"), new_user_path) %></p>
    <% if @anonymous_notes_count >= 10 %>
      <p><%= t ".counter_warning_html",
               :x_anonymous_notes => t(".x_anonymous_notes", :count => @anonymous_notes_count),
               :contribute_by_yourself => link_to(t(".counter_warning_guide_link.text"), t(".counter_warning_guide_link.url")),
               :community_can_help => link_to(t(".counter_warning_forum_link.text"), t(".counter_warning_forum_link.url")) %></p>
    <% end %>
    </div>
  <% end %>
  <p class="alert alert-warning" id="new-note-zoom-warning" hidden><%= t "javascripts.site.createnote_disabled_tooltip" %></p>
  <form action="#">
    <input type="hidden" name="lon" autocomplete="off">
    <input type="hidden" name="lat" autocomplete="off">
    <div class="mb-3">
      <textarea class="form-control" name="text" cols="40" rows="10" maxlength="2000" placeholder="<%= t(".advice") %>"></textarea>
    </div>
    <div>
      <input type="submit" name="add" value="<%= t(".add") %>" disabled="1" class="btn btn-primary">
    </div>
  </form>
</div>

app/views/notes/new_readonly.html.erb
<% set_title(t(".title")) %>

<%= render "sidebar_header", :title => t(".title") %>

<div class="note">
  <p class="alert alert-warning"><%= t(".warning") %></p>
</div>

app/views/notes/show.html.erb
<% set_title(t(".title", :id => @note.id)) %>

<%= render "sidebar_header", :title => t(".#{@note.status}_title", :note_name => @note.id) %>

<div>
  <h4><%= t(".description") %></h4>
  <div class="overflow-hidden ms-2">
    <%= note_description(@note.author, @note.description, current_user&.moderator? ? @note.comments.unscope(:where => :visible).first : @note.comments.first).to_html %>
  </div>

  <div class="details" data-coordinates="<%= @note.lat %>,<%= @note.lon %>" data-status="<%= @note.status %>">
    <p class="mb-2"><%= note_event("opened", @note.created_at, @note.author) %></p>
    <% if @note.status == "closed" %>
      <p class="mb-2"><%= note_event(@note.status, @note.closed_at, @note.all_comments.last.author) %></p>
    <% end %>
    <p>
      <%= t "browse.location" %>
      <%= link_to t(".coordinates_html",
                    :latitude => tag.span(number_with_delimiter(@note.lat), :class => "latitude"),
                    :longitude => tag.span(number_with_delimiter(@note.lon), :class => "longitude")),
                  root_path(:anchor => "map=18/#{@note.lat}/#{@note.lon}") %>
    </p>
  </div>

  <% if @note_includes_anonymous -%>
    <p class='alert alert-warning'><%= t ".anonymous_warning" %></p>
  <% end -%>

  <div class="row">
    <div class="col">
      <h4><%= t(".discussion") %></h4>
    </div>

    <% if current_user %>
      <div class="col-auto">
        <% if @note.subscribers.exists?(current_user.id) %>
          <%= tag.button t(".unsubscribe"),
                         :type => "button",
                         :class => "btn btn-sm btn-primary",
                         :name => "unsubscribe",
                         :data => { :method => "DELETE",
                                    :url => api_note_subscription_path(@note) } %>
        <% else %>
          <%= tag.button t(".subscribe"),
                         :type => "button",
                         :class => "btn btn-sm btn-primary",
                         :name => "subscribe",
                         :data => { :method => "POST",
                                    :url => api_note_subscription_path(@note) } %>
        <% end %>
      </div>
    <% end %>
  </div>

  <% if @note_comments.length > 0 %>
    <div class='note-comments'>
      <ul class="list-unstyled">
        <% @note_comments.each do |comment| %>
          <li id="c<%= comment.id %>">
            <small class='text-body-secondary'><%= note_event(comment.event, comment.created_at, comment.author) %></small>
            <div class="mx-2">
              <%= comment.body.to_html %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @note.status == "open" %>
    <% if current_user -%>
      <form class="mb-3" action="#">
        <div class="mb-3">
          <textarea class="form-control" name="text" cols="40" rows="5" maxlength="2000"></textarea>
        </div>
        <div id="comment-error" class="alert alert-danger p-2 mb-3" hidden>
        </div>
        <div class="d-flex flex-wrap gap-1">
          <% if current_user.moderator? -%>
            <%= button_tag t(".hide"), :name => "hide", :class => "btn btn-light",
                                       :data => { :method => "DELETE",
                                                  :url => api_note_url(@note, "json") } %>
          <% end -%>
          <%= button_tag t(".resolve"), :name => "close", :class => "btn btn-primary",
                                        :data => { :method => "POST",
                                                   :url => close_api_note_url(@note, "json"),
                                                   :default_action_text => t(".resolve"),
                                                   :comment_action_text => t(".comment_and_resolve") } %>
          <%= button_tag t(".comment"), :name => "comment", :class => "btn btn-primary", :disabled => true,
                                        :data => { :method => "POST",
                                                   :url => comment_api_note_url(@note, "json") } %>
        </div>
      </form>
    <% else -%>
      <p>
        <%= link_to t(".log_in_to_comment"), login_path(:referer => request.fullpath) %>
      </p>
    <% end -%>
  <% else %>
    <form class="mb-3" action="#">
      <input type="hidden" name="text" value="" autocomplete="off">
      <div id="comment-error" class="alert alert-danger p-2 mb-3" hidden>
      </div>
      <div class="d-flex flex-wrap gap-1">
        <% if @note.status != "hidden" and current_user and current_user.moderator? -%>
          <%= button_tag t(".hide"), :name => "hide", :class => "btn btn-light",
                                     :data => { :method => "DELETE",
                                                :url => api_note_url(@note, "json") } %>
        <% end -%>
        <% if current_user -%>
          <%= button_tag t(".reactivate"), :name => "reopen", :class => "btn btn-primary",
                                           :data => { :method => "POST",
                                                      :url => reopen_api_note_url(@note, "json") } %>
        <% end -%>
      </div>
    </form>
  <% end %>

  <% if current_user && current_user != @note.author %>
    <p>
      <small class="text-body-secondary">
        <%= t ".report_link_html", :link => report_link(t(".report"), @note) %>
        <% if @note.status == "open" %>
          <%= t ".other_problems_resolve", :link => report_link(t(".report"), @note) %>
        <% elsif @note.status == "closed" %>
          <%= t ".other_problems_resolved" %>
        <% end %>
      </small>
    </p>
  <% end %>

  <% if @note.freshly_closed? %>
    <small class="text-body-secondary">
      <%= t ".disappear_date_html", :disappear_in => friendly_date(@note.freshly_closed_until) %>
    </small>
  <% end %>
</div>