config/routes.rb
OpenStreetMap::Application.routes.draw do
  use_doorkeeper :scope => "oauth2" do
    controllers :authorizations => "oauth2_authorizations",
                :applications => "oauth2_applications",
                :authorized_applications => "oauth2_authorized_applications"
  end

  use_doorkeeper_openid_connect :scope => "oauth2" if Settings.key?(:doorkeeper_signing_key)

  # API
  namespace :api do
    get "capabilities" => "capabilities#show" # Deprecated, remove when 0.6 support is removed
    get "versions" => "versions#show"
  end

  scope "api/0.6", :module => :api do
    get "capabilities" => "capabilities#show"
    get "permissions" => "permissions#show"

    post "changeset/:id/upload" => "changesets#upload", :as => :changeset_upload, :id => /\d+/
    put "changeset/:id/close" => "changesets#close", :as => :changeset_close, :id => /\d+/
  end

  namespace :api, :path => "api/0.6" do
    resources :changesets, :only => [:index, :create]
    resources :changesets, :path => "changeset", :id => /\d+/, :only => [:show, :update] do
      resource :download, :module => :changesets, :only => :show
      resource :subscription, :controller => :changeset_subscriptions, :only => [:create, :destroy]
      resources :changeset_comments, :path => "comment", :only => :create
    end
    put "changeset/create" => "changesets#create", :as => nil
    post "changeset/:changeset_id/subscribe" => "changeset_subscriptions#create", :changeset_id => /\d+/, :as => nil
    post "changeset/:changeset_id/unsubscribe" => "changeset_subscriptions#destroy", :changeset_id => /\d+/, :as => nil

    resources :changeset_comments, :id => /\d+/, :only => :index do
      resource :visibility, :module => :changeset_comments, :only => [:create, :destroy]
    end
    post "changeset/comment/:changeset_comment_id/unhide" => "changeset_comments/visibilities#create", :changeset_comment_id => /\d+/, :as => nil
    post "changeset/comment/:changeset_comment_id/hide" => "changeset_comments/visibilities#destroy", :changeset_comment_id => /\d+/, :as => nil

    resources :nodes, :only => [:index, :create]
    resources :nodes, :path => "node", :id => /\d+/, :only => [:show, :update, :destroy] do
      scope :module => :nodes do
        resources :ways, :only => :index
        resources :relations, :only => :index
      end
      resources :versions, :path => "history", :controller => :old_nodes, :only => :index
      resource :version, :path => ":version", :version => /\d+/, :controller => :old_nodes, :only => :show do
        resource :redaction, :module => :old_nodes, :only => [:create, :destroy]
      end
    end
    put "node/create" => "nodes#create", :as => nil
    post "node/:node_id/:version/redact" => "old_nodes/redactions#create", :node_id => /\d+/, :version => /\d+/, :allow_delete => true, :as => nil

    resources :ways, :only => [:index, :create]
    resources :ways, :path => "way", :id => /\d+/, :only => [:show, :update, :destroy] do
      member do
        get :full, :action => :show, :full => true, :as => nil
      end
      scope :module => :ways do
        resources :relations, :only => :index
      end
      resources :versions, :path => "history", :controller => :old_ways, :only => :index
      resource :version, :path => ":version", :version => /\d+/, :controller => :old_ways, :only => :show do
        resource :redaction, :module => :old_ways, :only => [:create, :destroy]
      end
    end
    put "way/create" => "ways#create", :as => nil
    post "way/:way_id/:version/redact" => "old_ways/redactions#create", :way_id => /\d+/, :version => /\d+/, :allow_delete => true, :as => nil

    resources :relations, :only => [:index, :create]
    resources :relations, :path => "relation", :id => /\d+/, :only => [:show, :update, :destroy] do
      member do
        get :full, :action => :show, :full => true, :as => nil
      end
      scope :module => :relations do
        resources :relations, :only => :index
      end
      resources :versions, :path => "history", :controller => :old_relations, :only => :index
      resource :version, :path => ":version", :version => /\d+/, :controller => :old_relations, :only => :show do
        resource :redaction, :module => :old_relations, :only => [:create, :destroy]
      end
    end
    put "relation/create" => "relations#create", :as => nil
    post "relation/:relation_id/:version/redact" => "old_relations/redactions#create", :relation_id => /\d+/, :version => /\d+/, :allow_delete => true, :as => nil

    resource :map, :only => :show

    resources :tracepoints, :path => "trackpoints", :only => :index

    resources :users, :only => :index
    resources :users, :path => "user", :id => /\d+/, :only => :show
    resources :user_traces, :path => "user/gpx_files", :module => :users, :controller => :traces, :only => :index
    get "user/details" => "users#details"

    resources :user_preferences, :except => [:new, :create, :edit], :param => :preference_key, :path => "user/preferences" do
      collection do
        put "" => "user_preferences#update_all", :as => ""
      end
    end

    resources :messages, :path => "user/messages", :constraints => { :id => /\d+/ }, :only => [:create, :show, :update, :destroy]
    namespace :messages, :path => "user/messages" do
      resource :inbox, :only => :show
      resource :outbox, :only => :show
    end
    post "/user/messages/:id" => "messages#update", :as => nil

    resources :traces, :path => "gpx", :only => [:create, :show, :update, :destroy], :id => /\d+/ do
      scope :module => :traces do
        resource :data, :only => :show
      end
    end
    post "gpx/create" => "traces#create", :id => /\d+/, :as => :trace_create
    get "gpx/:id/details" => "traces#show", :id => /\d+/, :as => :trace_details

    # Map notes API
    resources :notes, :except => [:new, :edit, :update], :id => /\d+/, :controller => "notes" do
      collection do
        get "search"
        get "feed", :defaults => { :format => "rss" }
      end

      member do
        post "comment"
        post "close"
        post "reopen"
      end

      resource :subscription, :only => [:create, :destroy], :controller => "note_subscriptions"
    end

    resources :user_blocks, :only => [:show, :create], :id => /\d+/, :controller => "user_blocks"
    namespace :user_blocks, :path => "user/blocks" do
      resource :active_list, :path => "active", :only => :show
    end
  end

  # Data browsing
  get "/way/:id" => "ways#show", :id => /\d+/, :as => :way
  get "/way/:id/history" => "old_ways#index", :id => /\d+/, :as => :way_history
  resources :old_ways, :path => "/way/:id/history", :id => /\d+/, :version => /\d+/, :param => :version, :only => :show
  get "/node/:id" => "nodes#show", :id => /\d+/, :as => :node
  get "/node/:id/history" => "old_nodes#index", :id => /\d+/, :as => :node_history
  resources :old_nodes, :path => "/node/:id/history", :id => /\d+/, :version => /\d+/, :param => :version, :only => :show
  get "/relation/:id" => "relations#show", :id => /\d+/, :as => :relation
  get "/relation/:id/history" => "old_relations#index", :id => /\d+/, :as => :relation_history
  resources :old_relations, :path => "/relation/:id/history", :id => /\d+/, :version => /\d+/, :param => :version, :only => :show

  resources :changesets, :path => "changeset", :id => /\d+/, :only => :show do
    resource :subscription, :controller => :changeset_subscriptions, :only => [:show, :create, :destroy]
    namespace :changeset_comments, :as => :comments, :path => :comments do
      resource :feed, :only => :show, :defaults => { :format => "rss" }
    end
  end
  get "/changeset/:id/subscribe", :id => /\d+/, :to => redirect(:path => "/changeset/%{id}/subscription")
  get "/changeset/:id/unsubscribe", :id => /\d+/, :to => redirect(:path => "/changeset/%{id}/subscription")

  resources :notes, :path => "note", :id => /\d+/, :only => [:show, :new]

  get "/user/:display_name/history" => "changesets#index"
  get "/user/:display_name/history/feed" => "changesets#feed", :defaults => { :format => :atom }
  get "/user/:display_name/notes" => "notes#index", :as => :user_notes
  get "/history/friends" => "changesets#index", :friends => true, :as => "friend_changesets", :defaults => { :format => :html }
  get "/history/nearby" => "changesets#index", :nearby => true, :as => "nearby_changesets", :defaults => { :format => :html }

  get "/browse/way/:id",                :to => redirect(:path => "/way/%{id}")
  get "/browse/way/:id/history",        :to => redirect(:path => "/way/%{id}/history")
  get "/browse/node/:id",               :to => redirect(:path => "/node/%{id}")
  get "/browse/node/:id/history",       :to => redirect(:path => "/node/%{id}/history")
  get "/browse/relation/:id",           :to => redirect(:path => "/relation/%{id}")
  get "/browse/relation/:id/history",   :to => redirect(:path => "/relation/%{id}/history")
  get "/browse/changeset/:id",          :to => redirect(:path => "/changeset/%{id}")
  get "/browse/note/:id",               :to => redirect(:path => "/note/%{id}")
  get "/user/:display_name/edits",      :to => redirect(:path => "/user/%{display_name}/history")
  get "/user/:display_name/edits/feed", :to => redirect(:path => "/user/%{display_name}/history/feed")
  get "/browse/friends",                :to => redirect(:path => "/history/friends")
  get "/browse/nearby",                 :to => redirect(:path => "/history/nearby")
  get "/browse/changesets/feed",        :to => redirect(:path => "/history/feed")
  get "/browse/changesets",             :to => redirect(:path => "/history")
  get "/browse",                        :to => redirect(:path => "/history")

  # web site
  root :to => "site#index", :via => [:get, :post]
  get "/edit" => "site#edit"
  get "/copyright/:copyright_locale" => "site#copyright"
  get "/copyright" => "site#copyright"
  get "/welcome" => "site#welcome"
  get "/fixthemap" => "site#fixthemap"
  get "/help" => "site#help"

app/controllers/api/changesets/downloads_controller.rb
module Api
  module Changesets
    class DownloadsController < ApiController
      before_action :setup_user_auth

      authorize_resource :changeset

      before_action :set_request_formats

      ##
      # download the changeset as an osmChange document.
      #
      # to make it easier to revert diffs it would be better if the osmChange
      # format were reversible, i.e: contained both old and new versions of
      # modified elements. but it doesn't at the moment...
      #
      # this method cannot order the database changes fully (i.e: timestamp and
      # version number may be too coarse) so the resulting diff may not apply
      # to a different database. however since changesets are not atomic this
      # behaviour cannot be guaranteed anyway and is the result of a design
      # choice.
      def show
        changeset = Changeset.find(params[:changeset_id])

        # get all the elements in the changeset which haven't been redacted
        # and stick them in a big array.
        elements = if show_redactions?
                     [changeset.old_nodes,
                      changeset.old_ways,
                      changeset.old_relations].flatten
                   else
                     [changeset.old_nodes.unredacted,
                      changeset.old_ways.unredacted,
                      changeset.old_relations.unredacted].flatten
                   end

        # sort the elements by timestamp and version number, as this is the
        # almost sensible ordering available. this would be much nicer if
        # global (SVN-style) versioning were used - then that would be
        # unambiguous.
        elements.sort_by! { |e| [e.timestamp, e.version] }

        # generate an output element for each operation. note: we avoid looking
        # at the history because it is simpler - but it would be more correct to
        # check these assertions.
        @created = []
        @modified = []
        @deleted = []

        elements.each do |elt|
          if elt.version == 1
            # first version, so it must be newly-created.
            @created << elt
          elsif elt.visible
            # must be a modify
            @modified << elt
          else
            # if the element isn't visible then it must have been deleted
            @deleted << elt
          end
        end

        respond_to do |format|
          format.xml
        end
      end

      private

      def show_redactions?
        current_user&.moderator? && params[:show_redactions] == "true"
      end
    end
  end
end

app/helpers/changesets_helper.rb
module ChangesetsHelper
  def changeset_user_link(changeset)
    if changeset.user.status == "deleted"
      t("users.no_such_user.deleted")
    elsif changeset.user.data_public?
      link_to changeset.user.display_name, changeset.user, :class => "mw-100 d-inline-block align-bottom text-truncate text-wrap", :dir => "auto"
    else
      t("browse.anonymous")
    end
  end

  def changeset_details(changeset)
    if changeset.closed_at > Time.now.utc
      action = :created
      time = time_ago_in_words(changeset.created_at, :scope => :"datetime.distance_in_words_ago")
      title = l(changeset.created_at)
      datetime = changeset.created_at.xmlschema
    else
      action = :closed
      time = time_ago_in_words(changeset.closed_at, :scope => :"datetime.distance_in_words_ago")
      title = safe_join([t("changesets.show.created", :when => l(changeset.created_at)), "&#10;".html_safe, t("changesets.show.closed", :when => l(changeset.closed_at))])
      datetime = changeset.closed_at.xmlschema
    end

    if params.key?(:display_name)
      t "changesets.show.#{action}_ago_html", :time_ago => tag.time(time, :title => title, :datetime => datetime)
    else
      t "changesets.show.#{action}_ago_by_html", :time_ago => tag.time(time, :title => title, :datetime => datetime),
                                                 :user => changeset_user_link(changeset)
    end
  end

  def changeset_index_title(params, user)
    if params[:friends] && user
      t "changesets.index.title_followed"
    elsif params[:nearby] && user
      t "changesets.index.title_nearby"
    elsif params[:display_name]
      t "changesets.index.title_user", :user => params[:display_name]
    else
      t "changesets.index.title"
    end
  end

  def changeset_data(changeset)
    changeset_data = { :id => changeset.id }

    if changeset.bbox_valid?
      bbox = changeset.bbox.to_unscaled
      changeset_data[:bbox] = {
        :minlon => bbox.min_lon,
        :minlat => bbox.min_lat,
        :maxlon => bbox.max_lon,
        :maxlat => bbox.max_lat
      }
    end

    changeset_data
  end
end

app/views/changesets/_changeset.html.erb
<%= tag.li :id => "changeset_#{changeset.id}", :data => { :changeset => changeset_data(changeset) }, :class => "list-group-item list-group-item-action" do %>
  <p class="fs-6 text-truncate text-wrap mb-0">
    <a class="changeset_id link-body-emphasis stretched-link" href="<%= changeset_path(changeset) %>">
      <span><%= changeset.tags["comment"].to_s.presence || t("browse.no_comment") %></span>
    </a>
  </p>
  <div class="d-flex flex-nowrap gap-3 justify-content-between align-items-end">
    <div class="overflow-hidden pt-3">
      <%= changeset_details(changeset) %>
      &middot;
      <a class="changeset_id link-body-emphasis" href="<%= changeset_path(changeset) %>">
        #<%= changeset.id %>
      </a>
    </div>
    <div class="d-flex flex-column align-items-end text-body-secondary">
      <%= tag.div :class => ["d-flex align-items-baseline gap-1", { "opacity-50" => changeset.comments.empty? }],
                  :title => t(".comments", :count => changeset.comments.length) do %>
        <%= changeset.comments.length %>
        <svg width="12" height="12" viewBox="0 0 16 16" fill="currentColor">
          <% if changeset.comments.empty? %>
            <path d="M2.678 11.894a1 1 0 0 1 .287.801 11 11 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8 8 0 0 0 8 14c3.996 0 7-2.807 7-6s-3.004-6-7-6-7 2.808-7 6c0 1.468.617 2.83 1.678 3.894m-.493 3.905a22 22 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a10 10 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9 9 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105" />
          <% else %>
            <path d="M8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6-.097 1.016-.417 2.13-.771 2.966-.079.186.074.394.273.362 2.256-.37 3.597-.938 4.18-1.234A9 9 0 0 0 8 15" />
          <% end %>
        </svg>
      <% end %>
      <%= tag.div :class => ["d-flex align-items-baseline gap-1", { "opacity-50" => changeset.num_changes.zero? }],
                  :title => t(".changes", :count => changeset.num_changes) do %>
        <%= changeset.num_changes %>
        <svg width="12" height="12" viewBox="0 0 16 16" fill="currentColor">
          <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325" />
        </svg>
      <% end %>
    </div>
  </div>
<% end %>

app/views/changesets/_elements.html.erb
<%= turbo_frame_tag "changeset_#{type.pluralize}" do %>
  <%= render :partial => "paging_nav", :locals => { :type => type, :pages => pages } %>
  <ul class="list-unstyled browse-element-list" data-turbo="false">
    <% elements.each do |element| %>
      <%= element_list_item_with_strikethrough type, element do %>
        <%= t "printable_name.current_and_old_links_html",
              :current_link => link_to(printable_element_name(element), :controller => type.pluralize, :action => :show, :id => element.id[0]),
              :old_link => link_to(printable_element_version(element), :controller => "old_#{type.pluralize}", :action => :show, :id => element.id[0], :version => element.version) %>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/changesets/_not_found_message.html.erb
<div>
  <p><%= t ".sorry", :id => params[:id] %></p>
</div>

app/views/changesets/_paging_nav.html.erb
<h4 class="fs-5"><%= type_and_paginated_count(type, pages) %></h4>
<% if pages.page_count > 1 %>
  <%= sidebar_classic_pagination(pages, "#{type}_page") do |page|
        {
          :title => type_and_paginated_count(type, pages, page),
          :data => { :turbo => "true" }
        }
      end %>
<% end %>

app/views/changesets/history.html.erb
<% content_for :auto_discovery_link_tag do -%>
  <% unless params[:friends] or params[:nearby] -%>
    <%= auto_discovery_link_tag :atom, @params.to_h.merge(:before => nil, :xhr => nil, :action => :feed) %>
  <% end -%>
<% end -%>

<% set_title(changeset_index_title(params, current_user))
   @heading = if params[:display_name]
                t("changesets.index.title_user_link_html", :user_link => link_to(params[:display_name], user_path(params[:display_name])))
              else
                @title
              end %>

<%= render "sidebar_header", :title => @heading %>

<div class="changesets mx-n3">
  <div class="text-center loader">
    <div class="spinner-border" role="status">
      <span class="visually-hidden"><%= t("browse.start_rjs.loading") %></span>
    </div>
  </div>
</div>

app/views/changesets/index.html.erb
<% if @newer_changesets_id %>
  <div class="changeset_more my-3 text-center">
    <%= link_to t(".load_more"), url_for(@params.merge(:before => nil, :after => @newer_changesets_id)), :class => "btn btn-primary" %>
    <div class="text-center loader">
      <div class="spinner-border" role="status">
        <span class="visually-hidden"><%= t("browse.start_rjs.loading") %></span>
      </div>
    </div>
  </div>
<% end %>
<% if @changesets.present? %>
  <ol class="changesets list-group list-group-flush">
    <%= render @changesets %>
  </ol>
<% elsif params[:bbox] %>
  <p class="mx-3"><%= params[:before] ? t(".no_more_area") : t(".empty_area") %></p>
<% elsif params[:display_name] %>
  <p class="mx-3"><%= params[:before] ? t(".no_more_user") : t(".empty_user") %></p>
<% else %>
  <p class="mx-3"><%= params[:before] ? t(".no_more") : t(".empty") %></p>
<% end %>
<% if @older_changesets_id -%>
  <div class="changeset_more my-3 text-center">
    <%= link_to t(".load_more"), url_for(@params.merge(:before => @older_changesets_id, :after => nil)), :class => "btn btn-primary" %>
    <div class="text-center loader">
      <div class="spinner-border" role="status">
        <span class="visually-hidden"><%= t("browse.start_rjs.loading") %></span>
      </div>
    </div>
  </div>
<% end -%>

app/views/changesets/show.html.erb
<% set_title(t(".title", :id => @changeset.id)) %>

<%= render "sidebar_header", :title => t(".title", :id => @changeset.id) %>

<div class="browse-section">
  <p class="fs-6 overflow-x-auto">
    <%= linkify(@changeset.tags["comment"].to_s.presence || t("browse.no_comment")) %>
  </p>
  <%= tag.p :class => "details", :data => { :changeset => changeset_data(@changeset) } do %>
    <%= changeset_details(@changeset) %>
  <% end %>

  <%= render :partial => "browse/tag_details", :object => @changeset.tags.except("comment") %>

  <div class="row">
    <div class="col">
      <h4><%= t(".discussion") %></h4>
    </div>

    <% if current_user %>
      <div class="col-auto">
        <% if @changeset.subscribers.exists?(current_user.id) %>
          <%= tag.button t(".unsubscribe"),
                         :class => "btn btn-sm btn-primary",
                         :name => "unsubscribe",
                         :data => { :method => "DELETE",
                                    :url => api_changeset_subscription_path(@changeset) } %>
        <% else %>
          <%= tag.button t(".subscribe"),
                         :class => "btn btn-sm btn-primary",
                         :name => "subscribe",
                         :data => { :method => "POST",
                                    :url => api_changeset_subscription_path(@changeset) } %>
        <% end %>
      </div>
    <% end %>
  </div>

  <% if @comments.length > 0 %>
    <ul class="list-unstyled">
      <% @comments.each do |comment| %>
        <% next unless comment.visible || current_user&.moderator? %>
        <li id="c<%= comment.id %>">
          <small class='text-body-secondary'>
            <%= comment_by_options = { :time_ago => friendly_date_ago(comment.created_at),
                                       :user => link_to(comment.author.display_name, comment.author) }
                comment.visible ? t(".comment_by_html", **comment_by_options) : t(".hidden_comment_by_html", **comment_by_options) %>
            <% if current_user&.moderator? %>
              —
              <%= tag.button t(".#{comment.visible ? 'hide' : 'unhide'}_comment"),
                             :class => "btn btn-sm small btn-link link-secondary p-0 align-baseline",
                             :data => { :method => comment.visible ? "DELETE" : "POST",
                                        :url => api_changeset_comment_visibility_path(comment) } %>
            <% end %>
            <a href="#c<%= comment.id %>">
              <svg width="16" height="16" fill="currentColor">
                <path d="M4.715 6.542 3.343 7.914a3 3 0 1 0 4.243 4.243l1.828-1.829A3 3 0 0 0 8.586 5.5L8 6.086a1 1 0 0 0-.154.199 2 2 0 0 1 .861 3.337L6.88 11.45a2 2 0 1 1-2.83-2.83l.793-.792a4 4 0 0 1-.128-1.287z" />
                <path d="M6.586 4.672A3 3 0 0 0 7.414 9.5l.775-.776a2 2 0 0 1-.896-3.346L9.12 3.55a2 2 0 1 1 2.83 2.83l-.793.792c.112.42.155.855.128 1.287l1.372-1.372a3 3 0 1 0-4.243-4.243z" />
              </svg>
            </a>
          </small>
          <div class="mx-2">
            <%= comment.body.to_html %>
          </div>
        </li>
      <% end %>
    </ul>
  <% end %>

  <% unless current_user %>
    <p>
      <%= link_to(t(".join_discussion"), login_path(:referer => request.fullpath)) %>
    </p>
  <% end %>

  <% if current_user %>
    <% unless @changeset.open? %>
      <form action="#" class="mb-3">
        <div class="mb-3">
          <textarea class="form-control" name="text" cols="40" rows="5"></textarea>
        </div>
        <div id="comment-error" class="alert alert-danger p-2 mb-3" hidden>
        </div>
        <div>
          <%= tag.button t(".comment"),
                         :class => "btn btn-primary",
                         :name => "comment",
                         :disabled => true,
                         :data => { :method => "POST",
                                    :url => api_changeset_changeset_comments_path(@changeset) } %>
        </div>
      </form>
    <% else %>
      <p>
        <%= t(".still_open") %>
      </p>
    <% end %>
  <% end %>

  <% unless @ways.empty? %>
    <%= render :partial => "elements", :locals => { :type => "way", :elements => @ways, :pages => @way_pages } %>
  <% end %>

  <% unless @relations.empty? %>
    <%= render :partial => "elements", :locals => { :type => "relation", :elements => @relations, :pages => @relation_pages } %>
  <% end %>

  <% unless @nodes.empty? %>
    <%= render :partial => "elements", :locals => { :type => "node", :elements => @nodes, :pages => @node_pages } %>
  <% end %>
</div>

<div class='secondary-actions'>
  <%= link_to t(".changesetxml"), api_changeset_path(@changeset) %>
  &middot;
  <%= link_to t(".osmchangexml"), api_changeset_download_path(@changeset) %>
</div>

<% if @next_by_user || @prev_by_user %>
  <div class='secondary-actions'>
    <% if @prev_by_user %>
      <%= link_to @prev_by_user, :class => "icon-link" do %>
        <%= previous_page_svg_tag :height => 11 %>
        <%= @prev_by_user.id %>
      <% end %>
      &middot;
    <% end %>
    <%= user = (@prev_by_user || @next_by_user).user.display_name
        link_to tag.bdi(user), :controller => "changesets", :action => "index", :display_name => user %>
    <% if @next_by_user %>
      &middot;
      <%= link_to @next_by_user, :class => "icon-link" do %>
        <%= @next_by_user.id %>
        <%= next_page_svg_tag :height => 11 %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/changesets/timeout.html.erb
<p><%= t ".sorry" %></p>